'use strict';
const bcrypt = require('bcryptjs');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const users = await queryInterface.bulkInsert(
      'Users',
      [
        {
          username: 'memu',
          email: 'memu@email.com',
          password: bcrypt.hashSync('password'),
          dob: new Date('03-21-1995'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    );

    const quests = await queryInterface.bulkInsert(
      'Quests',
      [
        {
          title: 'Warring Matriarchs',
          description: 'The islands of Vidalia are at war. The Matriarchs seem unwilling to let go of their grudges.',
          creatorId: users[0].id,
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ],
      { returning: true }
    );

    const enemies = await queryInterface.bulkInsert(
      'Enemies',
      [
        {
          name: 'Aboleth',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 17,
          hitPoints: 135,
          hitDice: '18d10',
          strength: 21,
          dexterity: 9,
          constitution: 15,
          intelligence: 18,
          wisdom: 15,
          charisma: 18,
          challenge: 10,
          xpReward: 5900,
        },
        {
          name: 'Acolyte',
          size: 'Medium',
          type: 'Humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 10,
          hitPoints: 9,
          hitDice: '2d8',
          strength: 10,
          dexterity: 10,
          constitution: 10,
          intelligence: 10,
          wisdom: 14,
          charisma: 11,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Adult Black Dragon',
          size: 'Huge',
          type: 'Dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 195,
          hitDice: '17d12',
          strength: 23,
          dexterity: 14,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 14,
          xpReward: 11500,
        },
        {
          name: 'Adult Blue Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 225,
          hitDice: '18d12',
          strength: 25,
          dexterity: 10,
          constitution: 23,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 16,
          xpReward: 15000,
        },
        {
          name: 'Adult Brass Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 18,
          hitPoints: 172,
          hitDice: '15d12',
          strength: 23,
          dexterity: 10,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 13,
          xpReward: 10000,
        },
        {
          name: 'Adult Bronze Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 212,
          hitDice: '17d12',
          strength: 25,
          dexterity: 10,
          constitution: 23,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 15,
          xpReward: 13000,
        },
        {
          name: 'Adult Copper Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 18,
          hitPoints: 172,
          hitDice: '15d12',
          strength: 23,
          dexterity: 10,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 14,
          xpReward: 11500,
        },
        {
          name: 'Adult Gold Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '19d12',
          strength: 27,
          dexterity: 14,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 24,
          challenge: 17,
          xpReward: 18000,
        },
        {
          name: 'Adult Green Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 207,
          hitDice: '18d12',
          strength: 23,
          dexterity: 12,
          constitution: 21,
          intelligence: 18,
          wisdom: 15,
          charisma: 17,
          challenge: 15,
          xpReward: 13000,
        },
        {
          name: 'Adult Red Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '19d12',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 13,
          charisma: 21,
          challenge: 17,
          xpReward: 18000,
        },
        {
          name: 'Adult Silver Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 243,
          hitDice: '18d12',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 13,
          charisma: 21,
          challenge: 16,
          xpReward: 15000,
        },
        {
          name: 'Adult White Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '16d12',
          strength: 22,
          dexterity: 10,
          constitution: 22,
          intelligence: 8,
          wisdom: 12,
          charisma: 12,
          challenge: 13,
          xpReward: 10000,
        },
        {
          name: 'Air Elemental',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Nuetral',
          armorClass: 15,
          hitPoints: 90,
          hitDice: '12d10',
          strength: 14,
          dexterity: 20,
          constitution: 14,
          intelligence: 6,
          wisdom: 10,
          charisma: 6,
          challenge: 5,
          xpReward: 1800,
        },
        {
          name: 'Ancient Black Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 22,
          hitPoints: 367,
          hitDice: '21d20',
          strength: 27,
          dexterity: 14,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 21,
          xpReward: 33000,
        },
        {
          name: 'Ancient Blue Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Laeful Evil',
          armorClass: 22,
          hitPoints: 481,
          hitDice: '26d20',
          strength: 29,
          dexterity: 10,
          constitution: 27,
          intelligence: 18,
          wisdom: 17,
          charisma: 21,
          challenge: 23,
          xpReward: 50000,
        },
        {
          name: 'Ancient Brass Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 20,
          hitPoints: 297,
          hitDice: '17d20',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 20,
          xpReward: 25000,
        },
        {
          name: 'Ancient Bronze Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 22,
          hitPoints: 444,
          hitDice: '24d20',
          strength: 29,
          dexterity: 10,
          constitution: 27,
          intelligence: 18,
          wisdom: 17,
          charisma: 21,
          challenge: 22,
          xpReward: 41000,
        },
        {
          name: 'Ancient Copper Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 21,
          hitPoints: 350,
          hitDice: '20d20',
          strength: 27,
          dexterity: 12,
          constitution: 25,
          intelligence: 20,
          wisdom: 17,
          charisma: 19,
          challenge: 21,
          xpReward: 33000,
        },
        {
          name: 'Ancient Gold Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 22,
          hitPoints: 546,
          hitDice: '28d20',
          strength: 30,
          dexterity: 14,
          constitution: 29,
          intelligence: 18,
          wisdom: 17,
          charisma: 28,
          challenge: 24,
          xpReward: 62000,
        },
        {
          name: 'Ancient Green Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 21,
          hitPoints: 385,
          hitDice: '22d20',
          strength: 27,
          dexterity: 12,
          constitution: 25,
          intelligence: 20,
          wisdom: 17,
          charisma: 19,
          challenge: 22,
          xpReward: 41000,
        },
        {
          name: 'Ancient Red Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 22,
          hitPoints: 367,
          hitDice: '21d20',
          strength: 30,
          dexterity: 10,
          constitution: 29,
          intelligence: 18,
          wisdom: 15,
          charisma: 23,
          challenge: 24,
          xpReward: 62000,
        },
        {
          name: 'Ancient Silver Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 22,
          hitPoints: 487,
          hitDice: '25d20',
          strength: 30,
          dexterity: 10,
          constitution: 29,
          intelligence: 18,
          wisdom: 15,
          charisma: 23,
          challenge: 23,
          xpReward: 50000,
        },
        {
          name: 'Ancient White Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 20,
          hitPoints: 333,
          hitDice: '18d20',
          strength: 26,
          dexterity: 10,
          constitution: 26,
          intelligence: 10,
          wisdom: 13,
          charisma: 14,
          challenge: 20,
          xpReward: 25000,
        },
        {
          name: 'Androsphinx',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Lawful Nuetral',
          armorClass: 17,
          hitPoints: 199,
          hitDice: '19d10',
          strength: 22,
          dexterity: 10,
          constitution: 20,
          intelligence: 16,
          wisdom: 18,
          charisma: 23,
          challenge: 17,
          xpReward: 18000,
        },
        {
          name: 'Animated Armor',
          size: 'Medium',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 18,
          hitPoints: 33,
          hitDice: '6d8',
          strength: 14,
          dexterity: 11,
          constitution: 13,
          intelligence: 1,
          wisdom: 3,
          charisma: 1,
          challenge: 1,
          xpReward: 200,
        },
        {
          name: 'Ankheg',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 39,
          hitDice: '6d10',
          strength: 17,
          dexterity: 11,
          constitution: 13,
          intelligence: 1,
          wisdom: 13,
          charisma: 6,
          challenge: 2,
          xpReward: 250,
        },
        {
          name: 'Ape',
          size: 'Medium',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 18,
          hitPoints: 33,
          hitDice: '6d8',
          strength: 16,
          dexterity: 14,
          constitution: 14,
          intelligence: 6,
          wisdom: 12,
          charisma: 7,
          challenge: 0.5,
          xpReward: 100,
        },
        {
          name: 'Archmage',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 12,
          hitPoints: 99,
          hitDice: '18d8',
          strength: 10,
          dexterity: 14,
          constitution: 12,
          intelligence: 20,
          wisdom: 15,
          charisma: 16,
          challenge: 12,
          xpReward: 8400,
        },
        {
          name: 'Assassin',
          size: 'Medium',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 15,
          hitPoints: 78,
          hitDice: '12d8',
          strength: 11,
          dexterity: 16,
          constitution: 14,
          intelligence: 13,
          wisdom: 11,
          charisma: 10,
          challenge: 8,
          xpReward: 3900,
        },
        {
          name: 'Awakened Shrub',
          size: 'Small',
          type: 'plant',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 9,
          hitPoints: 10,
          hitDice: '3d6',
          strength: 3,
          dexterity: 8,
          constitution: 11,
          intelligence: 10,
          wisdom: 10,
          charisma: 6,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Awakened Tree',
          size: 'Huge',
          type: 'plant',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 49,
          hitDice: '7d12',
          strength: 19,
          dexterity: 6,
          constitution: 15,
          intelligence: 10,
          wisdom: 10,
          charisma: 7,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Axe Beak',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 19,
          hitDice: '3d10',
          strength: 3,
          dexterity: 8,
          constitution: 11,
          intelligence: 10,
          wisdom: 10,
          charisma: 6,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Azer',
          size: 'Medium',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Lawful Neutral',
          armorClass: 17,
          hitPoints: 39,
          hitDice: '6d8',
          strength: 17,
          dexterity: 12,
          constitution: 15,
          intelligence: 12,
          wisdom: 13,
          charisma: 10,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Baboon',
          size: 'Small',
          type: 'best',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 3,
          hitDice: '1d6',
          strength: 8,
          dexterity: 14,
          constitution: 11,
          intelligence: 4,
          wisdom: 12,
          charisma: 6,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Badger',
          size: 'Tiny',
          type: 'best',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 10,
          hitPoints: 3,
          hitDice: '1d4',
          strength: 4,
          dexterity: 11,
          constitution: 12,
          intelligence: 2,
          wisdom: 12,
          charisma: 4,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Balor',
          size: 'Huge',
          type: 'fiend',
          subtype: 'demon',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 262,
          hitDice: '21d12',
          strength: 26,
          dexterity: 15,
          constitution: 22,
          intelligence: 20,
          wisdom: 16,
          charisma: 22,
          challenge: 19,
          xpReward: 22000,
        },
        {
          name: 'Bandit',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any non-lawful alignment',
          armorClass: 12,
          hitPoints: 11,
          hitDice: '2d8',
          strength: 11,
          dexterity: 12,
          constitution: 12,
          intelligence: 10,
          wisdom: 10,
          charisma: 10,
          challenge: 0.125,
          xpReward: 25,
        },
        {
          name: 'Bandit Captain',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any non-lawful alignment',
          armorClass: 15,
          hitPoints: 65,
          hitDice: '10d8',
          strength: 11,
          dexterity: 16,
          constitution: 14,
          intelligence: 14,
          wisdom: 11,
          charisma: 14,
          challenge: 2,
          xpReward: 450,
        },        {
          name: 'Barbed Devil',
          size: 'Medium',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 15,
          hitPoints: 110,
          hitDice: '13d8',
          strength: 16,
          dexterity: 17,
          constitution: 18,
          intelligence: 12,
          wisdom: 14,
          charisma: 14,
          challenge: 5,
          xpReward: 1800,
        },
        {
          name: 'Basilisk',
          size: 'Medium',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 52,
          hitDice: '8d8',
          strength: 16,
          dexterity: 8,
          constitution: 15,
          intelligence: 2,
          wisdom: 8,
          charisma: 7,
          challenge: 3,
          xpReward: 700,
        },
        {
          name: 'Bat',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 1,
          hitDice: '1d4',
          strength: 2,
          dexterity: 15,
          constitution: 8,
          intelligence: 2,
          wisdom: 12,
          charisma: 4,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Bearded Devil',
          size: 'Medium',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 13,
          hitPoints: 52,
          hitDice: '8d8',
          strength: 16,
          dexterity: 15,
          constitution: 15,
          intelligence: 9,
          wisdom: 11,
          charisma: 11,
          challenge: 3,
          xpReward: 700,
        },
        {
          name: 'Behir',
          size: 'Huge',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Neutral Evil',
          armorClass: 17,
          hitPoints: 168,
          hitDice: '16d12',
          strength: 23,
          dexterity: 16,
          constitution: 18,
          intelligence: 7,
          wisdom: 14,
          charisma: 12,
          challenge: 11,
          xpReward: 7200,
        },
        {
          name: 'Berserker',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any chaotic alignment',
          armorClass: 13,
          hitPoints: 67,
          hitDice: '9d8',
          strength: 16,
          dexterity: 12,
          constitution: 17,
          intelligence: 19,
          wisdom: 11,
          charisma: 9,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Black Bear',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 19,
          hitDice: '3d8',
          strength: 15,
          dexterity: 10,
          constitution: 14,
          intelligence: 2,
          wisdom: 12,
          charisma: 7,
          challenge: 0.5,
          xpReward: 100,
        },
        {
          name: 'Black Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 17,
          hitPoints: 33,
          hitDice: '6d8',
          strength: 15,
          dexterity: 14,
          constitution: 13,
          intelligence: 10,
          wisdom: 11,
          charisma: 13,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Black Pudding',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any non-lawful alignment',
          armorClass: 7,
          hitPoints: 85,
          hitDice: '10d10',
          strength: 16,
          dexterity: 5,
          constitution: 16,
          intelligence: 1,
          wisdom: 6,
          charisma: 1,
          challenge: 4,
          xpReward: 1100,
        },
        {
          name: 'Blink Dog',
          size: 'Medium',
          type: 'fey',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 13,
          hitPoints: 22,
          hitDice: '4d8',
          strength: 12,
          dexterity: 17,
          constitution: 12,
          intelligence: 10,
          wisdom: 13,
          charisma: 11,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Blood Hawk',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 7,
          hitDice: '2d6',
          strength: 6,
          dexterity: 14,
          constitution: 10,
          intelligence: 3,
          wisdom: 14,
          charisma: 5,
          challenge: 0.125,
          xpReward: 25,
        },
        {
          name: 'Blue Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 17,
          hitPoints: 52,
          hitDice: '8d8',
          strength: 17,
          dexterity: 10,
          constitution: 15,
          intelligence: 12,
          wisdom: 11,
          charisma: 15,
          challenge: 3,
          xpReward: 700,
        },
        {
          name: 'Boar',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 17,
          hitPoints: 1,
          hitDice: '2d8',
          strength: 13,
          dexterity: 11,
          constitution: 12,
          intelligence: 2,
          wisdom: 9,
          charisma: 5,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Bone Devil',
          size: 'Large',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 142,
          hitDice: '15d10',
          strength: 18,
          dexterity: 16,
          constitution: 18,
          intelligence: 13,
          wisdom: 14,
          charisma: 16,
          challenge: 12,
          xpReward: 8400,
        },
        {
          name: 'Brass Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 16,
          hitPoints: 16,
          hitDice: '3d8',
          strength: 15,
          dexterity: 10,
          constitution: 13,
          intelligence: 10,
          wisdom: 11,
          charisma: 13,
          challenge: 1,
          xpReward: 100,
        },
        {
          name: 'Bronze Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 17,
          hitPoints: 32,
          hitDice: '5d8',
          strength: 17,
          dexterity: 10,
          constitution: 15,
          intelligence: 12,
          wisdom: 11,
          charisma: 15,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Brown Bear',
          size: 'Medium',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 34,
          hitDice: '4d10',
          strength: 19,
          dexterity: 10,
          constitution: 16,
          intelligence: 2,
          wisdom: 13,
          charisma: 7,
          challenge: 1,
          xpReward: 200,
        },
        {
          name: 'Bulette',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 17,
          hitPoints: 94,
          hitDice: '9d10',
          strength: 19,
          dexterity: 11,
          constitution: 21,
          intelligence: 2,
          wisdom: 10,
          charisma: 5,
          challenge: 1,
          xpReward: 200,
        },
        {
          name: 'Camel',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 9,
          hitPoints: 15,
          hitDice: '2d10',
          strength: 16,
          dexterity: 8,
          constitution: 14,
          intelligence: 2,
          wisdom: 8,
          charisma: 5,
          challenge: 0.125,
          xpReward: 25,
        },
        {
          name: 'Cat',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 2,
          hitDice: '1d4',
          strength: 3,
          dexterity: 15,
          constitution: 10,
          intelligence: 3,
          wisdom: 12,
          charisma: 7,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Centaur',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Neutral Good',
          armorClass: 12,
          hitPoints: 45,
          hitDice: '6d10',
          strength: 18,
          dexterity: 14,
          constitution: 14,
          intelligence: 9,
          wisdom: 13,
          charisma: 11,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Chain Devil',
          size: 'Medium',
          type: 'fiend',
          subtype: 'devil',
          alignment: 'Lawful Evil',
          armorClass: 16,
          hitPoints: 85,
          hitDice: '10d8',
          strength: 18,
          dexterity: 15,
          constitution: 18,
          intelligence: 11,
          wisdom: 12,
          charisma: 14,
          challenge: 8,
          xpReward: 3900,
        },
        {
          name: 'Chimera',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 14,
          hitPoints: 114,
          hitDice: '12d10',
          strength: 19,
          dexterity: 11,
          constitution: 19,
          intelligence: 3,
          wisdom: 14,
          charisma: 10,
          challenge: 6,
          xpReward: 2300,
        },
        {
          name: 'Chuul',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 16,
          hitPoints: 93,
          hitDice: '11d10',
          strength: 19,
          dexterity: 10,
          constitution: 16,
          intelligence: 35,
          wisdom: 11,
          charisma: 5,
          challenge: 4,
          xpReward: 1100,
        },
        {
          name: 'Clay Golem',
          size: 'Large',
          type: 'construct',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 133,
          hitDice: '14d10',
          strength: 20,
          dexterity: 9,
          constitution: 18,
          intelligence: 3,
          wisdom: 8,
          charisma: 1,
          challenge: 9,
          xpReward: 5000,
        },
        {
          name: 'Cloaker',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Chaotic Neutral',
          armorClass: 14,
          hitPoints: 78,
          hitDice: '12d10',
          strength: 17,
          dexterity: 15,
          constitution: 12,
          intelligence: 13,
          wisdom: 12,
          charisma: 14,
          challenge: 8,
          xpReward: 3900,
        },
        {
          name: 'Cloud Giant',
          size: 'Huge',
          type: 'giant',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 14,
          hitPoints: 200,
          hitDice: '16d12',
          strength: 27,
          dexterity: 10,
          constitution: 2,
          intelligence: 12,
          wisdom: 16,
          charisma: 16,
          challenge: 9,
          xpReward: 5000,
        },
        {
          name: 'Cockatrice',
          size: 'Small',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 27,
          hitDice: '6d6',
          strength: 6,
          dexterity: 12,
          constitution: 12,
          intelligence: 2,
          wisdom: 13,
          charisma: 5,
          challenge: 6,
          xpReward: 2300,
        },
        {
          name: 'Commoner',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 10,
          hitPoints: 4,
          hitDice: '1d8',
          strength: 10,
          dexterity: 10,
          constitution: 10,
          intelligence: 10,
          wisdom: 10,
          charisma: 10,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Constrictor Snake',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 13,
          hitDice: '2d10',
          strength: 15,
          dexterity: 14,
          constitution: 12,
          intelligence: 1,
          wisdom: 10,
          charisma: 3,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Copper Dragon Wyrmling',
          size: 'Medium',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 16,
          hitPoints: 22,
          hitDice: '4d8',
          strength: 15,
          dexterity: 12,
          constitution: 13,
          intelligence: 14,
          wisdom: 11,
          charisma: 13,
          challenge: 1,
          xpReward: 200,
        },
        {
          name: 'Couatl',
          size: 'Medium',
          type: 'celestial',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 97,
          hitDice: '13d8',
          strength: 16,
          dexterity: 20,
          constitution: 17,
          intelligence: 18,
          wisdom: 20,
          charisma: 18,
          challenge: 4,
          xpReward: 1100,
        },
        {
          name: 'Crab',
          size: 'Tiny',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 2,
          hitDice: '1d4',
          strength: 2,
          dexterity: 11,
          constitution: 10,
          intelligence: 1,
          wisdom: 8,
          charisma: 2,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Crocodile',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 19,
          hitDice: '2d10',
          strength: 15,
          dexterity: 10,
          constitution: 13,
          intelligence: 1,
          wisdom: 10,
          charisma: 5,
          challenge: 0.5,
          xpReward: 100,
        },
        {
          name: 'Cult Fanatic',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any evil alignment',
          armorClass: 12,
          hitPoints: 13,
          hitDice: '2d10',
          strength: 15,
          dexterity: 14,
          constitution: 12,
          intelligence: 1,
          wisdom: 10,
          charisma: 3,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Cultist',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any evil alignment',
          armorClass: 12,
          hitPoints: 9,
          hitDice: '2d8',
          strength: 11,
          dexterity: 12,
          constitution: 10,
          intelligence: 10,
          wisdom: 11,
          charisma: 10,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Dark Mantle',
          size: 'Small',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 11,
          hitPoints: 22,
          hitDice: '5d6',
          strength: 16,
          dexterity: 12,
          constitution: 13,
          intelligence: 2,
          wisdom: 10,
          charisma: 5,
          challenge: 0.5,
          xpReward: 100,
        },
        {
          name: 'Death Dog',
          size: 'Medium',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Neutral Evil',
          armorClass: 12,
          hitPoints: 39,
          hitDice: '6d8',
          strength: 15,
          dexterity: 14,
          constitution: 14,
          intelligence: 3,
          wisdom: 13,
          charisma: 6,
          challenge: 1,
          xpReward: 200,
        },
        {
          name: 'Deep Gnome Svirfneblin',
          size: 'Small',
          type: 'humanoid',
          subtype: 'gnome',
          alignment: 'Neutral Good',
          armorClass: 15,
          hitPoints: 16,
          hitDice: '3d6',
          strength: 16,
          dexterity: 14,
          constitution: 14,
          intelligence: 12,
          wisdom: 10,
          charisma: 9,
          challenge: 0.5,
          xpReward: 50,
        },
        {
          name: 'Deer',
          size: 'Medium',
          type: 'best',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 13,
          hitPoints: 4,
          hitDice: '1d8',
          strength: 11,
          dexterity: 16,
          constitution: 11,
          intelligence: 2,
          wisdom: 14,
          charisma: 5,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Deva',
          size: 'Small',
          type: 'celestial',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 17,
          hitPoints: 136,
          hitDice: '16d8',
          strength: 18,
          dexterity: 18,
          constitution: 18,
          intelligence: 17,
          wisdom: 20,
          charisma: 20,
          challenge: 10,
          xpReward: 5900,
        },
        {
          name: 'Dire Wolf',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 14,
          hitPoints: 37,
          hitDice: '5d10',
          strength: 17,
          dexterity: 15,
          constitution: 15,
          intelligence: 3,
          wisdom: 12,
          charisma: 7,
          challenge: 1,
          xpReward: 200,
        },
        {
          name: 'Djinni',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 17,
          hitPoints: 161,
          hitDice: '14d10',
          strength: 21,
          dexterity: 15,
          constitution: 22,
          intelligence: 15,
          wisdom: 16,
          charisma: 20,
          challenge: 11,
          xpReward: 7200,
        },
        {
          name: 'Doppleganger',
          size: 'Medium',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 14,
          hitPoints: 54,
          hitDice: '5d6',
          strength: 16,
          dexterity: 12,
          constitution: 15,
          intelligence: 12,
          wisdom: 12,
          charisma: 8,
          challenge: 5,
          xpReward: 1800,
        },
        {
          name: 'Draft Horse',
          size: 'Large',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 10,
          hitPoints: 19,
          hitDice: '3d10',
          strength: 16,
          dexterity: 12,
          constitution: 13,
          intelligence: 2,
          wisdom: 10,
          charisma: 5,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Dragon Turtle',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 20,
          hitPoints: 341,
          hitDice: '22d20',
          strength: 25,
          dexterity: 10,
          constitution: 20,
          intelligence: 10,
          wisdom: 12,
          charisma: 12,
          challenge: 17,
          xpReward: 18000,
        },
        {
          name: 'Dretch',
          size: 'Small',
          type: 'fiend',
          subtype: 'demon',
          alignment: 'Chaotic Evil',
          armorClass: 11,
          hitPoints: 18,
          hitDice: '4d6',
          strength: 11,
          dexterity: 11,
          constitution: 12,
          intelligence: 5,
          wisdom: 8,
          charisma: 3,
          challenge: 0.25,
          xpReward: 25,
        },
        {
          name: 'Drider',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 123,
          hitDice: '13d10',
          strength: 16,
          dexterity: 16,
          constitution: 18,
          intelligence: 13,
          wisdom: 14,
          charisma: 12,
          challenge: 6,
          xpReward: 2300,
        },
        {
          name: 'Drow',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'elf',
          alignment: 'Neutral Evil',
          armorClass: 15,
          hitPoints: 13,
          hitDice: '3d8',
          strength: 10,
          dexterity: 14,
          constitution: 10,
          intelligence: 11,
          wisdom: 11,
          charisma: 12,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Druid',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'Chaotic Evil',
          armorClass: 11,
          hitPoints: 27,
          hitDice: '5d8',
          strength: 10,
          dexterity: 12,
          constitution: 13,
          intelligence: 12,
          wisdom: 15,
          charisma: 11,
          challenge: 2,
          xpReward: 450,
        },
        {
          name: 'Dryad',
          size: 'Large',
          type: 'monstrosity',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 123,
          hitDice: '13d10',
          strength: 16,
          dexterity: 16,
          constitution: 18,
          intelligence: 13,
          wisdom: 14,
          charisma: 12,
          challenge: 6,
          xpReward: 2300,
        },
        {
          name: 'Dryad',
          size: 'Medium',
          type: 'fey',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 11,
          hitPoints: 22,
          hitDice: '5d8',
          strength: 10,
          dexterity: 12,
          constitution: 11,
          intelligence: 14,
          wisdom: 15,
          charisma: 18,
          challenge: 1,
          xpReward: 200,
        },
        {
          name: 'Eagle',
          size: 'Small',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 3,
          hitDice: '1d6',
          strength: 6,
          dexterity: 15,
          constitution: 10,
          intelligence: 2,
          wisdom: 14,
          charisma: 7,
          challenge: 0,
          xpReward: 10,
        },
        {
          name: 'Earth Elemental',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Neutral',
          armorClass: 17,
          hitPoints: 126,
          hitDice: '12d10',
          strength: 20,
          dexterity: 8,
          constitution: 20,
          intelligence: 5,
          wisdom: 10,
          charisma: 5,
          challenge: 5,
          xpReward: 1800,
        },
        {
          name: 'Efreeti',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 17,
          hitPoints: 200,
          hitDice: '16d10',
          strength: 22,
          dexterity: 12,
          constitution: 24,
          intelligence: 16,
          wisdom: 15,
          charisma: 16,
          challenge: 11,
          xpReward: 7200,
        },
        {
          name: 'Elephant',
          size: 'Huge',
          type: 'beast',
          subtype: 'none',
          alignment: 'unaligned',
          armorClass: 12,
          hitPoints: 76,
          hitDice: '8d12',
          strength: 22,
          dexterity: 9,
          constitution: 17,
          intelligence: 3,
          wisdom: 11,
          charisma: 12,
          challenge: 4,
          xpReward: 1100,
        },
        {
          name: 'Guard',
          size: 'Medium',
          type: 'humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 16,
          hitPoints: 11,
          hitDice: '2d8',
          strength: 13,
          dexterity: 12,
          constitution: 12,
          intelligence: 10,
          wisdom: 11,
          charisma: 10,
          challenge: 0.125,
          xpReward: 25,
        },

      ],
      { returning: true }
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Enemies', null, {});
    await queryInterface.bulkDelete('Quests', null, {});
    return queryInterface.bulkDelete('Users', null, {});
  }
};
