'use strict';
const bcrypt = require('bcryptjs');

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const users = await queryInterface.bulkInsert(
      'Users',
      [
        {
          username: 'memu',
          email: 'memu@email.com',
          password: bcrypt.hashSync('password'),
          dob: new Date('03-21-1995'),
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      { returning: true }
    );

    const quests = await queryInterface.bulkInsert(
      'Quests',
      [
        {
          title: 'Warring Matriarchs',
          description: 'The islands of Vidalia are at war. The Matriarchs seem unwilling to let go of their grudges.',
          creatorId: users[0].id,
          createdAt: new Date(),
          updatedAt: new Date(),
        }
      ],
      { returning: true }
    );

    const enemies = await queryInterface.bulkInsert(
      'Enemies',
      [
        {
          name: 'Aboleth',
          size: 'Large',
          type: 'aberration',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 17,
          hitPoints: 135,
          hitDice: '18d10',
          strength: 21,
          dexterity: 9,
          constitution: 15,
          intelligence: 18,
          wisdom: 15,
          charisma: 18,
          challenge: 10,
          xpReward: 5900,
        },
        {
          name: 'Acolyte',
          size: 'Medium',
          type: 'Humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 10,
          hitPoints: 9,
          hitDice: '2d8',
          strength: 10,
          dexterity: 10,
          constitution: 10,
          intelligence: 10,
          wisdom: 14,
          charisma: 11,
          challenge: 0.25,
          xpReward: 50,
        },
        {
          name: 'Adult Black Dragon',
          size: 'Huge',
          type: 'Dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 195,
          hitDice: '17d12',
          strength: 23,
          dexterity: 14,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 14,
          xpReward: 11500,
        },
        {
          name: 'Adult Blue Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 225,
          hitDice: '18d12',
          strength: 25,
          dexterity: 10,
          constitution: 23,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 16,
          xpReward: 15000,
        },
        {
          name: 'Adult Brass Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 18,
          hitPoints: 172,
          hitDice: '15d12',
          strength: 23,
          dexterity: 10,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 13,
          xpReward: 10000,
        },
        {
          name: 'Adult Bronze Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 212,
          hitDice: '17d12',
          strength: 25,
          dexterity: 10,
          constitution: 23,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 15,
          xpReward: 13000,
        },
        {
          name: 'Adult Copper Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 18,
          hitPoints: 172,
          hitDice: '15d12',
          strength: 23,
          dexterity: 10,
          constitution: 21,
          intelligence: 14,
          wisdom: 13,
          charisma: 17,
          challenge: 14,
          xpReward: 11500,
        },
        {
          name: 'Adult Gold Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '19d12',
          strength: 27,
          dexterity: 14,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 24,
          challenge: 17,
          xpReward: 18000,
        },
        {
          name: 'Adult Green Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Evil',
          armorClass: 19,
          hitPoints: 207,
          hitDice: '18d12',
          strength: 23,
          dexterity: 12,
          constitution: 21,
          intelligence: 18,
          wisdom: 15,
          charisma: 17,
          challenge: 15,
          xpReward: 13000,
        },
        {
          name: 'Adult Red Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '19d12',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 13,
          charisma: 21,
          challenge: 17,
          xpReward: 18000,
        },
        {
          name: 'Adult Silver Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 19,
          hitPoints: 243,
          hitDice: '18d12',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 13,
          charisma: 21,
          challenge: 16,
          xpReward: 15000,
        },
        {
          name: 'Adult White Dragon',
          size: 'Huge',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 19,
          hitPoints: 256,
          hitDice: '16d12',
          strength: 22,
          dexterity: 10,
          constitution: 22,
          intelligence: 8,
          wisdom: 12,
          charisma: 12,
          challenge: 13,
          xpReward: 10000,
        },
        {
          name: 'Air Elemental',
          size: 'Large',
          type: 'elemental',
          subtype: 'none',
          alignment: 'Nuetral',
          armorClass: 15,
          hitPoints: 90,
          hitDice: '12d10',
          strength: 14,
          dexterity: 20,
          constitution: 14,
          intelligence: 6,
          wisdom: 10,
          charisma: 6,
          challenge: 5,
          xpReward: 1800,
        },
        {
          name: 'Ancient Black Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 22,
          hitPoints: 367,
          hitDice: '21d20',
          strength: 27,
          dexterity: 14,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 21,
          xpReward: 33000,
        },
        {
          name: 'Ancient Black Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Evil',
          armorClass: 22,
          hitPoints: 367,
          hitDice: '21d20',
          strength: 27,
          dexterity: 14,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 21,
          xpReward: 33000,
        },
        {
          name: 'Ancient Blue Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Laeful Evil',
          armorClass: 22,
          hitPoints: 481,
          hitDice: '26d20',
          strength: 29,
          dexterity: 10,
          constitution: 27,
          intelligence: 18,
          wisdom: 17,
          charisma: 21,
          challenge: 23,
          xpReward: 50000,
        },
        {
          name: 'Ancient Brass Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 20,
          hitPoints: 297,
          hitDice: '17d20',
          strength: 27,
          dexterity: 10,
          constitution: 25,
          intelligence: 16,
          wisdom: 15,
          charisma: 19,
          challenge: 20,
          xpReward: 25000,
        },
        {
          name: 'Ancient Bronze Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Lawful Good',
          armorClass: 22,
          hitPoints: 444,
          hitDice: '24d20',
          strength: 29,
          dexterity: 10,
          constitution: 27,
          intelligence: 18,
          wisdom: 17,
          charisma: 21,
          challenge: 22,
          xpReward: 41000,
        },
        {
          name: 'Ancient Copper Dragon',
          size: 'Gargantuan',
          type: 'dragon',
          subtype: 'none',
          alignment: 'Chaotic Good',
          armorClass: 21,
          hitPoints: 350,
          hitDice: '20d20',
          strength: 27,
          dexterity: 12,
          constitution: 25,
          intelligence: 20,
          wisdom: 17,
          charisma: 19,
          challenge: 21,
          xpReward: 33000,
        },
        {
          name: 'Guard',
          size: 'Medium',
          type: 'Humanoid',
          subtype: 'any race',
          alignment: 'any alignment',
          armorClass: 16,
          hitPoints: 11,
          hitDice: '2d8',
          strength: 13,
          dexterity: 12,
          constitution: 12,
          intelligence: 10,
          wisdom: 11,
          charisma: 10,
          challenge: 0.125,
          xpReward: 25,
        },
      ],
      { returning: true }
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('Quests', null, {});
    return queryInterface.bulkDelete('Users', null, {});
  }
};
